---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
        image: jaeestee/ml-buildings-api:latest
        volumes:
            - ./config.yaml:/config.yaml
            #- ./cnn-split/test:/cnn-split/test #example